# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json

version: 2

project_name: test-goreleaser-npm-trusted

before:
  hooks:
    - go mod tidy

builds:
  - id: cli
    main: ./cmd/test-goreleaser-npm-trusted/main.go
    binary: test-goreleaser-npm-trusted
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - id: default
    ids:
      - cli
    formats:
      - tar.gz

npms:
  - id: npm
    name: "@frenchi/test-goreleaser-npm-trusted"
    description: Test GoReleaser + npm Trusted Publishing.
    license: MIT
    author: "FR <dev@example.com>"
    repository: https://github.com/frenchi/test-goreleaser-npm-trusted
    bugs: https://github.com/frenchi/test-goreleaser-npm-trusted/issues
    keywords:
      - cli
      - goreleaser
      - npm
      - oidc
    access: public
    format: tar.gz
    url_template: "https://github.com/frenchi/test-goreleaser-npm-trusted/releases/download/{{ .Tag }}/{{ .ArtifactName }}"