name: goreleaser

on:
  push:
    tags:
      - "v*-goreleaser"

permissions:
  contents: write
  id-token: write

jobs:
  release:
    environment: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Set up Node for npm Trusted Publishing
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Ensure latest npm (>= 11.5.1)
        run: npm install -g npm@latest

      - name: Toolchain info
        run: |
          node --version
          npm --version
          npm config get registry
          npm config set loglevel silly

      - name: Mask potential tokens
        run: |
          echo "::add-mask::${NODE_AUTH_TOKEN}"
          echo "::add-mask::${NPM_TOKEN}"

      - name: Env snapshot (sanitized)
        run: |
          printenv | sort | sed -E 's/(NODE_AUTH_TOKEN|NPM_TOKEN)=.*/\1=REDACTED/g'

      # Inject token only for token scenarios
      - name: Set token for token-allowed scenarios (v0.0.2-goreleaser, v0.0.3-goreleaser)
        if: ${{ (github.ref_name == 'v0.0.2-goreleaser' || github.ref_name == 'v0.0.3-goreleaser') }}
        run: echo "NODE_AUTH_TOKEN=${NPM_TOKEN}" >> $GITHUB_ENV
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Ensure no token for OIDC scenarios
      - name: Ensure no token for OIDC scenarios (v0.0.1-goreleaser, v0.0.4-goreleaser)
        if: ${{ (github.ref_name == 'v0.0.1-goreleaser' || github.ref_name == 'v0.0.4-goreleaser') }}
        run: echo "NODE_AUTH_TOKEN=" >> $GITHUB_ENV

      # npm requires a dist-tag when publishing a prerelease version (e.g., 0.0.2-goreleaser)
      - name: Set npm dist-tag for prerelease version
        run: echo "NPM_CONFIG_TAG=goreleaser" >> $GITHUB_ENV

      - name: npm whoami (expect no OIDC)
        run: npm whoami || true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser-pro
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
          NPM_CONFIG_LOGLEVEL: silly
